//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /afs/asu.edu/users/p/m/o/pmohan6/EEE591Brunhav/ProjPart4/Submission/primitives/dffbW.vp
//  Source template: dffbW
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
// Parameter bitWidth 	= 1
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

/////////////////////
// dffbW.vp


// To instantiate a module, first you have to 
// generate the module and then instantiate it
// bitWidth (_GENESIS2_INHERITANCE_PRIORITY_) = 1
//

// Top module without inputs or outputs
module dffbW_unq6
	#(parameter SIZE=32)
	(
	input logic [SIZE-1:0] d,
	input logic clk,
	input logic rst,
	input logic en,
	output logic [SIZE-1:0] q
	);
	
	always_ff @(posedge clk) begin
		if (en) begin
			if (~rst) begin
				q <= {SIZE{1'd0}};
			end
			else begin
				q <= d;
			end
		end
	end

endmodule: dffbW_unq6
